export const DEFAULT_PATTERN_LABEL = "デフォルト";
export const MAX_TRIP_DAYS = 365;
export const MAX_LOGS_PER_TRIP = 50;

export const PG_UNIQUE_VIOLATION = "23505";

export const ERROR_MSG = {
  TRIP_NOT_FOUND: "Trip not found",
  SCHEDULE_NOT_FOUND: "Schedule not found",
  PATTERN_NOT_FOUND: "Pattern not found",
  CANNOT_DELETE_DEFAULT: "Cannot delete default pattern",
  INVALID_JSON: "Invalid JSON",
  INTERNAL_ERROR: "Internal server error",
  DATE_ORDER: "End date must be on or after start date",
  SHARED_NOT_FOUND: "Shared trip not found",
  CANDIDATE_NOT_FOUND: "Candidate not found",
  CONFLICT: "Resource was modified by another user",
  USER_NOT_FOUND: "User not found",
  ALREADY_MEMBER: "Already a member",
  CANNOT_CHANGE_OWN_ROLE: "Cannot change own role",
  MEMBER_NOT_FOUND: "Member not found",
  CANNOT_REMOVE_SELF: "Cannot remove yourself",
  INVALID_REORDER: "Some schedules do not belong to this pattern",
  INVALID_CANDIDATE_REORDER: "Some schedules are not candidates of this trip",
  DAY_NOT_FOUND: "Day not found",
  GITHUB_API_FAILED: "Failed to create feedback issue",
  GITHUB_NOT_CONFIGURED: "Feedback is not configured",
  LIMIT_TRIPS: "Trip limit reached",
  LIMIT_SCHEDULES: "Schedule limit reached",
  LIMIT_PATTERNS: "Pattern limit reached",
  LIMIT_MEMBERS: "Member limit reached",
  CANNOT_FRIEND_SELF: "Cannot send friend request to yourself",
  ALREADY_FRIENDS: "Already friends or request pending",
  FRIEND_REQUEST_NOT_FOUND: "Friend request not found",
  FRIEND_NOT_FOUND: "Friend not found",
  LIMIT_FRIENDS: "Friend limit reached",
  INVALID_PASSWORD: "Invalid password",
  ACCOUNT_NOT_FOUND: "Account not found",
  UNAUTHORIZED: "Unauthorized",
  TOO_MANY_REQUESTS: "Too many requests",
  BOOKMARK_LIST_NOT_FOUND: "Bookmark list not found",
  BOOKMARK_NOT_FOUND: "Bookmark not found",
  LIMIT_BOOKMARK_LISTS: "Bookmark list limit reached",
  LIMIT_BOOKMARKS: "Bookmark limit reached",
  BOOKMARK_OWNER_MISMATCH: "Some bookmarks do not belong to user",
  SCHEDULE_TRIP_MISMATCH: "Some schedules do not belong to trip",
  GROUP_NOT_FOUND: "Group not found",
  LIMIT_GROUPS: "Group limit reached",
  LIMIT_GROUP_MEMBERS: "Group member limit reached",
  ALREADY_GROUP_MEMBER: "Already a group member",
  GROUP_MEMBER_NOT_FOUND: "Group member not found",
} as const;
